CREATE TABLE JM3007_ONETOMANY_BI_COURSE(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50)
);

CREATE TABLE JM3007_ONETOMANY_BI_ASSIGNMENT(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
COURSE_ID BIGINT,
FOREIGN KEY (COURSE_ID) REFERENCES JM3007_ONETOMANY_BI_COURSE(ID)
);