CREATE TABLE JM3007_MANYTOMANY_UNI_Person (
    id BIGINT  AUTO_INCREMENT,
    name varchar,
    PRIMARY KEY ( id )
);

CREATE TABLE JM3007_MANYTOMANY_UNI_Address (
    id BIGINT AUTO_INCREMENT,
    number VARCHAR(255) ,
    street VARCHAR(255) ,
    PRIMARY KEY ( id )
);

CREATE TABLE JM3007_MANYTOMANY_UNI_Person_JM3007_MANYTOMANY_UNI_Address (
    Person_id BIGINT NOT NULL ,
    addresses_id BIGINT NOT NULL
);

ALTER TABLE JM3007_MANYTOMANY_UNI_Person_JM3007_MANYTOMANY_UNI_Address
ADD CONSTRAINT addresses_id_fk
FOREIGN KEY (addresses_id) REFERENCES JM3007_MANYTOMANY_UNI_Address;

ALTER TABLE JM3007_MANYTOMANY_UNI_Person_JM3007_MANYTOMANY_UNI_Address
ADD CONSTRAINT Person_id_fk
FOREIGN KEY (Person_id) REFERENCES JM3007_MANYTOMANY_UNI_Person;